# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 06:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredProfile',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=120)),
                ('last_seen', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(help_text="Enter 'M' or 'F'", max_length=1)),
                ('date_of_birth', models.DateField()),
                ('air_id', models.CharField(max_length=20)),
                ('mailing_street', models.CharField(max_length=64)),
                ('mailing_optional', models.CharField(max_length=64)),
                ('mailing_city', models.CharField(max_length=64)),
                ('mailing_state', models.CharField(max_length=15)),
                ('mailing_zip', models.CharField(max_length=10)),
                ('mailing_country', models.CharField(max_length=64)),
                ('residence_country', models.CharField(max_length=64)),
                ('foreign_currency_default', models.CharField(max_length=64)),
                ('other_coverage', models.CharField(help_text="Enter 'Y' or 'N'", max_length=1)),
                ('other_insurance_co', models.CharField(max_length=64)),
                ('other_plan_name', models.CharField(max_length=64)),
                ('other_plan_id', models.CharField(max_length=64)),
                ('medicare_part_a', models.CharField(help_text="Enter 'Y' or 'N'", max_length=1)),
                ('medicare_part_b', models.CharField(help_text="Enter 'Y' or 'N'", max_length=1)),
                ('medicare_id', models.CharField(max_length=64)),
                ('full_time_student', models.CharField(help_text="Enter 'Y' or 'N'", max_length=1)),
                ('has_dependent', models.CharField(help_text="Enter 'Y' or 'N'", max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
