# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20190509_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredprofile',
            name='has_dependent',
        ),
        migrations.AddField(
            model_name='claim',
            name='receipt_file',
            field=models.FileField(default='0', upload_to='store', verbose_name='Receipt as File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='receipt_image',
            field=models.ImageField(default='0', upload_to='store', verbose_name='Receipt as Image'),
            preserve_default=False,
        ),
    ]
