# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_insuredprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuredprofile',
            old_name='user',
            new_name='username',
        ),
    ]
