# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20190406_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
