# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20190322_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentprofile',
            name='insured',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
