# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20190813_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship_to_insured',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Self', 'Self')], max_length=6, verbose_name='Relationship to insured'),
        ),
    ]
