# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='slug',
            new_name='profile_slug',
        ),
    ]
