# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20190412_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
