# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 05:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20190322_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentprofile',
            name='insured',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL),
        ),
    ]
