# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20190307_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredprofile',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
