# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_report_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dependent_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='submission.DependentProfile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insured_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.InsuredProfile'),
        ),
    ]
