# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20190329_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='other_accident_related',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=3, verbose_name='Due to other accident?'),
            preserve_default=False,
        ),
    ]
