# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20190423_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='auto_accident_related',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=3, verbose_name='Due to auto accident?'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('m', 'Medical'), ('d', 'Dental'), ('v', 'Vision'), ('h', 'Hearing'), ('p', 'Prescription')], max_length=1, verbose_name='Claim Type'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='employment_related',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=3, verbose_name='Due to employment-related accident?'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='full_time_student',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=3, verbose_name='Was patient full-time student at time of service?'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='other_accident_related',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=3, verbose_name='Due to other accident?'),
        ),
        migrations.AlterField(
            model_name='dependentprofile',
            name='full_time_student',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, verbose_name='Is dependent full-time student?'),
        ),
        migrations.AlterField(
            model_name='dependentprofile',
            name='relationship_to_insured',
            field=models.CharField(choices=[('s', 'Spouse'), ('c', 'Child')], max_length=1, verbose_name='Relationship to insured'),
        ),
        migrations.AlterField(
            model_name='insuredprofile',
            name='has_dependent',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=3, verbose_name='Does insured have dependents?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicare_part_a',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, null=True, verbose_name='Medicare Part A coverage?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medicare_part_b',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, null=True, verbose_name='Medicare Part B coverage?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_coverage',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1, null=True, verbose_name='Other health insurance coverage?'),
        ),
    ]
