# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20190426_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='report',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='submission.Report'),
        ),
    ]
