# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20190426_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentprofile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
