# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_dependentprofile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='dependent_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='submission.DependentProfile'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='insured_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submission.InsuredProfile'),
        ),
    ]
