# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_auto_20190502_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
